### ISSUE TITLE
Open form will not start

### ISSUE THREAD

**Issue by iLeoLion** [josegomez/epicor-editor#10]
Installed the extension and configured but the 'Epicor Customization (OPEN)' does nothing instead of spawning a form. 
I can't go on to complete the setup.
No error or warning is throw

**Comment by gingerhelp** [comment]
@iLeoLion a few suggestions:

1. Did you download the helper files and extract them into your client directory?  Links for them are located at https://marketplace.visualstudio.com/items?itemName=josecgomez.epicor-editor

2. When you downloaded the helper ZIP file, did you right-click the file, go to Properties, and see whether you needed to click that 'Unblock' button?  I didn't need to do that myself but Jose noted it in his video.  Windows might be blocking the files since they were downloaded from the Internet and are EXE / DLL files.

3. Do you have .Net 4.7.2 installed?

**Comment by iLeoLion** [comment]
I have done all the thing above and still it does not work.
If I start the customization with the debug in Visual Studio the app starts and it goes on.
Studio Code won't work.

**Comment by gingerhelp** [comment]
Hmm - I am on VSCode as well and it is working alright on my end with the latest helper files (I just downloaded them fresh just in case there was something in the latest build).  What does your extension settings look like in VSCode?  This is what mine looks like:

![image](https://user-images.githubusercontent.com/51887706/65440963-918b5900-ddf7-11e9-8bf4-c47cf3234a8e.png)

Do all of the paths you have defined exist?

**Comment by josegomez** [comment]
Can you look at the log file this creates a log in your Epicor folder. What does the log say?
What does your config look like?

**Comment by iLeoLion** [comment]
Ok so my VS Code looks like this.
![111](https://user-images.githubusercontent.com/23149054/65490046-b1c91f80-deac-11e9-84dc-7406482fb060.PNG)


I tried the extension on VS too but after the folder configuration and 'Open' it throws me an error: 
devenv.exe - Application Error (0xe0434352) occurred in the application at location 0x0000000075533522

**Comment by iLeoLion** [comment]
I did it. Turn out in the VSC code extension page there is not a link for the 10.2.4, but in the VS extension there is. So I downloaded it and now it works. 
Thanks for all the support!

**Comment by josegomez** [comment]
I have updated the VSCode page to include the link to the 400 library

**Comment by dhshane** [comment]
I'm running the VS Code Extension for Epicor 10 Customization in VS 2019.  When I click on the BAQ Entry the following error this thrown.  Any idea what the problem is?
![BAQ Entry Error](https://user-images.githubusercontent.com/4316294/68078254-97c60b00-fd8f-11e9-8b9e-684c5c1a01ef.PNG)
